### ISSUE TITLE
error when training on 1 gpu

### ISSUE THREAD

**Issue by Pixie8888** [CVMI-Lab/PLA#16]
Hi,
Thanks for releasing code! When I training S3DIS on one gpu, I got an error below. It seems that not all modules are participated during training? How to solve it?
![image](https://github.com/CVMI-Lab/PLA/assets/72333326/7f4b3ca7-19ec-4557-8096-e80e79949a9a)

**Comment by Dingry** [comment]
This issue is likely caused by the caption_logit_scale not being utilized in the loss computation. To verify if the caption loss is zero, you can set find_unused_parameters=True.  Note that this problem is more likely to occur when working with fewer GPUs (fewer scenes in a batch) due to missing 2D image data in certain scenes in S3DIS.

**Comment by Pixie8888** [comment]
Thanks! setting find_unused_parameters=True works.
